name: Rust - test constant_memory feature

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run the integration tests for the constant_memory feature set
      run: cargo test --test integration --features constant_memory
